import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import ItemsProvider from "@/contexts/context";
import { Bounce, ToastContainer } from "react-toastify";


const Oswaldfont = Oswald({
  variable: "--oswald-font",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog | Your exercise companion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" data-theme="dark"
      className={`${Oswaldfont.variable} h-full antialiased`}
    >
            {/* google font used*/}
      <body className={`min-h-full flex flex-col font-arial`}> 
        <ItemsProvider>
          <Nav/>
          <main className="flex-1">
            {children}
          </main>
        </ItemsProvider>
        <Footer/>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
